Front-end Initial page
maujogue/transcendance pull request #41
Opened 2024-04-08 13:58 UTC by maujogue

Created the front-end interface of our Pong, on which we will build upon :
- One initial Landing page to present the game app and the team who created it.
- One game Page with a collapsable sidebar and a few different pages, most of which are still temporary.
- When the game first loads, it appears black. You have to navigate to another page and come back for it to be displayed properly.
- There are modals for login and register. To access the game page, you have to click on login, which currently does not interact with the backend.
- The landing page is responsive for mobile devices, the game page not so much, yet.
- When clicking the drop-up (Boula), the game restarts, not ideal.

2024-04-08 14:18 UTC, boulatrousse requested changes
- `LandingSpace` is empty
- NavBar active selection is not accurate, it is still on "Home" even when we click on other page
- `https://127.0.0.1:8001/` does not print anything, empty page

2024-04-08 15:36 UTC, gclement42 submitted a review, later dismissed

2024-04-09 08:58 UTC, maujogue commented
all issues mentioned by @boulatrousse are now fixed 💯

2024-04-09 09:02 UTC, gclement42 approved these changes

2024-04-09 10:20 UTC, MarcelCerdan approved these changes

2024-04-09 10:21 UTC, MarcelCerdan approved these changes

2024-04-09 10:25 UTC, merged